import type { Car } from "../src/types/car.js";
import type { UserPreferences } from "../src/types/preferences.js";

export const fixtureCars: Car[] = [
  {
    id: "budget-sedan",
    make: "Test",
    model: "Budget Sedan",
    year: 2024,
    price: 20000,
    bodyType: "sedan",
    fuelType: "gas",
    drivetrain: "fwd",
    transmission: "cvt",
    mpg: 36,
    horsepower: 150,
    reliabilityScore: 90,
    safetyRating: 5,
    cargoSpace: 14,
    seating: 5,
    acceleration: 9.0,
    features: [],
    tags: ["budget"],
  },
  {
    id: "family-suv-awd",
    make: "Test",
    model: "Family SUV",
    year: 2024,
    price: 38000,
    bodyType: "suv",
    fuelType: "hybrid",
    drivetrain: "awd",
    transmission: "automatic",
    mpg: 38,
    horsepower: 220,
    reliabilityScore: 85,
    safetyRating: 5,
    cargoSpace: 36,
    seating: 7,
    acceleration: 7.5,
    features: [],
    tags: ["family"],
  },
  {
    id: "performance-coupe",
    make: "Test",
    model: "Performance Coupe",
    year: 2024,
    price: 70000,
    bodyType: "coupe",
    fuelType: "gas",
    drivetrain: "rwd",
    transmission: "manual",
    mpg: 20,
    horsepower: 450,
    reliabilityScore: 75,
    safetyRating: 4,
    cargoSpace: 10,
    seating: 2,
    acceleration: 3.5,
    features: [],
    tags: ["performance"],
  },
  {
    id: "luxury-ev-suv",
    make: "Test",
    model: "Luxury EV SUV",
    year: 2024,
    price: 55000,
    bodyType: "suv",
    fuelType: "ev",
    drivetrain: "awd",
    transmission: "single-speed",
    mpg: 110,
    horsepower: 350,
    reliabilityScore: 72,
    safetyRating: 5,
    cargoSpace: 30,
    seating: 5,
    acceleration: 4.5,
    features: [],
    tags: ["luxury"],
  },
];

export function makePreferences(overrides: Partial<UserPreferences> = {}): UserPreferences {
  return {
    budget: { min: 15000, max: 80000 },
    priorities: {
      price: 1,
      reliability: 1,
      fuelEconomy: 1,
      performance: 1,
      space: 1,
      safety: 1,
    },
    ...overrides,
  };
}
